# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

cache:
  directories:
    - $HOME/.m2

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -alenka538@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always